version: '3.8'

services:
  
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-episodite
    container_name: vue-episodite
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    

volumes:
    data-volume:
    node_modules: